python_technologies = [
    "Django",
    "Flask",
    "SQL",
    "PostgreSQL",
    "Web",
    "Docker",
    "Scrapy",
    "Selenium",
    "Pyppeteer",
    "Playwright",
    "AWS",
    "Kafka",
    "Redis",
    "NoSQL",
    "ReactJS",
    "TypeScript",
    "Python",
    "CSS",
    "JS",
    "JavaScript",
    "Azure",
    "REST",
    "Git",
    "Jira",
    "FastAPI",
    "DRF",
    "Django REST Framework",
    "Angular",
    "Vue",
    "React",
    "Kubernetes",
    "NumPy",
    "Pandas",
    "Tableau",
    "Jupyter",
    "MongoDB",
    "BentoML",
    "Linux",
    "OOP",
    "asyncio",
]

english_levels = ["Upper-Intermediate", "Advanced", "Intermediate", "Pre-Intermediate"]
